/* The following code was generated by JFlex 1.4.3 on 25-10-14 00:56 */

package com.intellij.torquescript;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.intellij.torquescript.psi.TSTypes;
import com.intellij.psi.TokenType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 25-10-14 00:56 from the specification file
 * <tt>C:/Users/Lukas/SkyDrive/IllusionalGames/TorqueScriptIDEA/src/com/intellij/torquescript/TorqueScript.flex</tt>
 */
class TSLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\15\1\0\1\11\1\14\22\0\1\11\1\62\1\17"+
    "\1\0\1\10\1\7\1\56\1\20\1\42\1\43\1\55\1\4\1\50"+
    "\1\52\1\2\1\16\12\1\1\6\1\51\1\61\1\54\1\53\1\63"+
    "\1\65\1\31\1\13\1\24\1\30\1\3\1\21\1\35\1\41\1\26"+
    "\1\5\1\33\1\32\1\5\1\23\1\27\1\37\1\5\1\40\1\34"+
    "\1\25\1\22\1\5\1\36\3\5\1\46\1\0\1\47\1\57\1\5"+
    "\1\0\1\31\1\13\1\24\1\30\1\3\1\21\1\35\1\41\1\26"+
    "\1\5\1\33\1\32\1\5\1\23\1\27\1\37\1\5\1\40\1\34"+
    "\1\25\1\22\1\12\1\36\3\5\1\44\1\60\1\45\1\64\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\4\1\6"+
    "\1\7\1\1\1\10\2\4\1\1\1\11\2\1\13\4"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\2\0\1\36\1\4\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\0\1\4\1\45"+
    "\1\46\1\0\1\47\1\0\1\50\3\4\1\35\2\4"+
    "\1\51\1\52\11\4\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\0\1\71\1\36\1\0\1\4\1\0\2\4"+
    "\1\72\1\73\11\4\1\74\1\75\1\76\1\77\1\100"+
    "\3\4\1\101\10\4\1\102\7\4\1\103\6\4\1\104"+
    "\1\4\1\105\1\4\1\106\1\4\1\107\1\110\2\4"+
    "\1\111\1\112\1\113\1\114\2\4\1\115\1\116";

  private static int [] zzUnpackAction() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a"+
    "\0\u0360\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da"+
    "\0\u0510\0\u0546\0\u057c\0\u05b2\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\66\0\u05e8\0\u061e\0\u0654\0\u068a"+
    "\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\66\0\66\0\66"+
    "\0\u07ce\0\u0804\0\242\0\u083a\0\66\0\66\0\66\0\u0870"+
    "\0\66\0\66\0\u02be\0\u08a6\0\u08dc\0\66\0\u032a\0\u032a"+
    "\0\u0360\0\u0360\0\u0912\0\u0948\0\u097e\0\u0144\0\u09b4\0\u09ea"+
    "\0\u0144\0\u0144\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\66\0\66\0\u0c3c\0\66"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\u0c72\0\u0ca8\0\66\0\u0cde\0\242\0\u0d14\0\u0870\0\u0d4a"+
    "\0\u0d80\0\u0db6\0\u0144\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4"+
    "\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\66\0\66\0\66\0\66"+
    "\0\u0144\0\u0fd2\0\u1008\0\u103e\0\u0144\0\u1074\0\u10aa\0\u10e0"+
    "\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u0144\0\u1224\0\u125a"+
    "\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u0144\0\u139e\0\u13d4"+
    "\0\u140a\0\u1440\0\u1476\0\u14ac\0\u0144\0\u14e2\0\u1518\0\u154e"+
    "\0\u0144\0\u1584\0\u15ba\0\u0144\0\u15f0\0\u1626\0\66\0\u0144"+
    "\0\u0144\0\66\0\u165c\0\u1692\0\u0144\0\u0144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\13\1\17\1\20"+
    "\1\21\1\22\1\7\1\23\1\24\1\25\1\26\1\7"+
    "\1\27\1\30\2\7\1\31\1\7\1\32\1\33\1\34"+
    "\1\7\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\67\0\1\3\1\61"+
    "\1\62\63\0\1\63\65\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\11\7\1\64\7\7\30\0"+
    "\1\65\47\0\1\66\12\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\21\7\32\0\1\67\62\0"+
    "\1\70\1\0\1\70\4\0\2\70\5\0\21\70\12\0"+
    "\1\71\14\0\1\70\1\0\1\70\4\0\2\70\5\0"+
    "\21\70\12\0\1\72\22\0\2\13\1\0\1\73\1\13"+
    "\51\0\1\7\1\0\1\7\1\0\1\7\3\0\1\13"+
    "\1\14\1\7\1\73\1\13\3\0\21\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\17\7"+
    "\1\74\1\7\41\0\1\13\66\0\1\75\35\0\1\76"+
    "\11\0\15\77\1\0\1\77\1\100\46\77\15\101\1\0"+
    "\2\101\1\102\45\101\1\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\1\7\1\103\4\7\1\104"+
    "\12\7\25\0\1\7\1\0\1\105\1\0\1\7\4\0"+
    "\2\7\5\0\11\7\1\106\7\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\10\7\1\107"+
    "\10\7\25\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\5\0\10\7\1\110\10\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\1\111\1\7"+
    "\1\112\16\7\25\0\1\7\1\0\1\113\1\0\1\7"+
    "\4\0\2\7\5\0\10\7\1\114\10\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\13\7"+
    "\1\115\5\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\5\7\1\116\7\7\1\117\1\120"+
    "\2\7\25\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\5\0\20\7\1\121\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\10\7\1\122\10\7"+
    "\25\0\1\7\1\0\1\123\1\0\1\7\4\0\2\7"+
    "\5\0\21\7\76\0\1\124\1\125\1\126\64\0\1\127"+
    "\1\130\65\0\1\131\65\0\1\132\65\0\1\133\1\0"+
    "\1\134\63\0\1\135\65\0\1\136\3\0\1\137\61\0"+
    "\1\140\4\0\1\141\14\0\1\142\43\0\1\143\12\0"+
    "\1\144\65\0\1\63\2\0\1\145\45\0\1\145\14\0"+
    "\1\7\1\0\1\7\1\0\1\7\4\0\2\7\5\0"+
    "\13\7\1\146\5\7\25\0\1\70\1\0\1\70\1\0"+
    "\1\70\1\147\3\0\2\70\5\0\21\70\25\0\1\7"+
    "\1\0\1\150\1\0\1\7\4\0\2\7\5\0\21\7"+
    "\24\0\14\75\2\0\50\75\1\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\2\7\1\151\16\7"+
    "\25\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\5\0\17\7\1\152\1\7\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\15\7\1\153\3\7"+
    "\25\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\5\0\13\7\1\154\5\7\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\1\7\1\106\5\0\21\7\25\0"+
    "\1\7\1\0\1\7\1\0\1\7\4\0\2\7\5\0"+
    "\1\155\20\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\4\7\1\156\14\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\13\7"+
    "\1\157\5\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\2\7\1\160\16\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\5\7"+
    "\1\161\13\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\3\7\1\106\15\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\5\7"+
    "\1\162\13\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\3\7\1\163\15\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\4\7"+
    "\1\164\14\7\77\0\1\165\66\0\1\166\65\0\1\167"+
    "\65\0\1\170\12\0\1\144\1\0\1\62\63\0\1\7"+
    "\1\0\1\171\1\0\1\7\4\0\2\7\5\0\21\7"+
    "\25\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\5\0\10\7\1\172\10\7\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\3\7\1\173\15\7"+
    "\25\0\1\7\1\0\1\174\1\0\1\7\4\0\2\7"+
    "\5\0\21\7\25\0\1\7\1\0\1\175\1\0\1\7"+
    "\4\0\2\7\5\0\21\7\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\10\7\1\176\10\7"+
    "\25\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\5\0\10\7\1\177\10\7\25\0\1\7\1\0\1\200"+
    "\1\0\1\7\4\0\2\7\5\0\21\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\14\7"+
    "\1\201\4\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\4\7\1\202\14\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\11\7"+
    "\1\203\7\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\12\7\1\204\6\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\1\7"+
    "\1\205\17\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\12\7\1\206\6\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\4\7"+
    "\1\207\14\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\5\0\10\7\1\210\10\7\25\0\1\7"+
    "\1\0\1\7\1\0\1\7\4\0\2\7\5\0\1\7"+
    "\1\211\17\7\25\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\1\7\1\212\5\0\21\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\17\7\1\213"+
    "\1\7\25\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\5\0\11\7\1\214\7\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\3\7\1\215"+
    "\15\7\25\0\1\7\1\0\1\216\1\0\1\7\4\0"+
    "\2\7\5\0\21\7\25\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\10\7\1\217\10\7\25\0"+
    "\1\7\1\0\1\7\1\0\1\7\4\0\2\7\5\0"+
    "\17\7\1\220\1\7\25\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\5\7\1\221\13\7\25\0"+
    "\1\7\1\0\1\7\1\0\1\7\4\0\2\7\5\0"+
    "\3\7\1\222\15\7\25\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\11\7\1\223\7\7\25\0"+
    "\1\7\1\0\1\7\1\0\1\7\4\0\2\7\5\0"+
    "\11\7\1\224\7\7\25\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\4\7\1\225\14\7\25\0"+
    "\1\7\1\0\1\226\1\0\1\7\4\0\2\7\5\0"+
    "\21\7\25\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\5\0\20\7\1\227\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\14\7\1\230\4\7"+
    "\25\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\5\0\2\7\1\231\16\7\25\0\1\7\1\0\1\7"+
    "\1\0\1\7\4\0\2\7\5\0\6\7\1\232\12\7"+
    "\25\0\1\7\1\0\1\7\1\0\1\7\4\0\2\7"+
    "\5\0\20\7\1\233\25\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\4\7\1\234\14\7\25\0"+
    "\1\7\1\0\1\7\1\0\1\7\4\0\2\7\5\0"+
    "\6\7\1\235\12\7\25\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\5\0\4\7\1\236\14\7\25\0"+
    "\1\7\1\0\1\7\1\0\1\7\2\0\1\237\1\0"+
    "\2\7\5\0\21\7\25\0\1\7\1\0\1\240\1\0"+
    "\1\7\4\0\2\7\5\0\21\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\2\7\1\241"+
    "\16\7\25\0\1\7\1\0\1\7\1\0\1\7\2\0"+
    "\1\242\1\0\2\7\5\0\21\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\3\7\1\243"+
    "\15\7\25\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\5\0\6\7\1\244\12\7\25\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\5\0\12\7\1\245"+
    "\6\7\25\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\5\0\2\7\1\246\16\7\24\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5832];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\32\1\10\11\11\1\3\11\2\0\2\1"+
    "\3\11\1\1\2\11\1\0\2\1\1\11\1\0\1\1"+
    "\1\0\23\1\2\11\1\1\11\11\1\1\1\0\1\11"+
    "\1\1\1\0\1\1\1\0\15\1\4\11\46\1\1\11"+
    "\2\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  TSLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  TSLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
        return;

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { return TSTypes.SEMICOLON;
          }
        case 79: break;
        case 67: 
          { return TSTypes.WHILE;
          }
        case 80: break;
        case 7: 
          { return TSTypes.MODULO;
          }
        case 81: break;
        case 36: 
          { return TSTypes.STREQUAL;
          }
        case 82: break;
        case 42: 
          { return TSTypes.IN;
          }
        case 83: break;
        case 39: 
          { return TSTypes.STRING;
          }
        case 84: break;
        case 2: 
          { return TSTypes.INTEGER;
          }
        case 85: break;
        case 19: 
          { return TSTypes.GT;
          }
        case 86: break;
        case 48: 
          { return TSTypes.EQUAL;
          }
        case 87: break;
        case 77: 
          { return TSTypes.DATABLOCK;
          }
        case 88: break;
        case 32: 
          { return TSTypes.PLUSASSIGN;
          }
        case 89: break;
        case 11: 
          { return TSTypes.RPAREN;
          }
        case 90: break;
        case 78: 
          { return TSTypes.SINGLETON;
          }
        case 91: break;
        case 75: 
          { return TSTypes.FUNCTION;
          }
        case 92: break;
        case 26: 
          { return TSTypes.EXCLAMATION;
          }
        case 93: break;
        case 6: 
          { return TSTypes.COLON;
          }
        case 94: break;
        case 60: 
          { return TSTypes.INTERNALNAMERECUR;
          }
        case 95: break;
        case 63: 
          { return TSTypes.NOTSTREQUAL;
          }
        case 96: break;
        case 73: 
          { return TSTypes.SWITCHSTR;
          }
        case 97: break;
        case 66: 
          { return TSTypes.BREAK;
          }
        case 98: break;
        case 53: 
          { return TSTypes.ORASSIGN;
          }
        case 99: break;
        case 40: 
          { return TSTypes.TAG;
          }
        case 100: break;
        case 3: 
          { return TSTypes.DOT;
          }
        case 101: break;
        case 22: 
          { return TSTypes.BITAND;
          }
        case 102: break;
        case 10: 
          { return TSTypes.LPAREN;
          }
        case 103: break;
        case 33: 
          { return TSTypes.COLONCOLON;
          }
        case 104: break;
        case 8: 
          { return TokenType.WHITE_SPACE;
          }
        case 105: break;
        case 5: 
          { return TSTypes.PLUS;
          }
        case 106: break;
        case 41: 
          { return TSTypes.IF;
          }
        case 107: break;
        case 27: 
          { return TSTypes.QUESTION;
          }
        case 108: break;
        case 59: 
          { return TSTypes.NEW;
          }
        case 109: break;
        case 16: 
          { return TSTypes.COMMA;
          }
        case 110: break;
        case 55: 
          { return TSTypes.LE;
          }
        case 111: break;
        case 21: 
          { return TSTypes.TIMES;
          }
        case 112: break;
        case 61: 
          { return TSTypes.SHIFTRASSIGN;
          }
        case 113: break;
        case 34: 
          { return TSTypes.VAR;
          }
        case 114: break;
        case 35: 
          { return TSTypes.MODULOASSIGN;
          }
        case 115: break;
        case 70: 
          { return TSTypes.RETURN;
          }
        case 116: break;
        case 68: 
          { return TSTypes.ASSERT;
          }
        case 117: break;
        case 47: 
          { return TSTypes.GE;
          }
        case 118: break;
        case 49: 
          { return TSTypes.TIMESASSIGN;
          }
        case 119: break;
        case 46: 
          { return TSTypes.BITRSHIFT;
          }
        case 120: break;
        case 23: 
          { return TSTypes.BITXOR;
          }
        case 121: break;
        case 56: 
          { return TSTypes.BITLSHIFT;
          }
        case 122: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 123: break;
        case 37: 
          { yybegin(YYINITIAL); return TSTypes.COMMENT;
          }
        case 124: break;
        case 76: 
          { return TSTypes.FOREACHSTR;
          }
        case 125: break;
        case 58: 
          { return TSTypes.FOR;
          }
        case 126: break;
        case 4: 
          { return TSTypes.ID;
          }
        case 127: break;
        case 31: 
          { return TSTypes.PLUSPLUS;
          }
        case 128: break;
        case 62: 
          { return TSTypes.SHIFTLASSIGN;
          }
        case 129: break;
        case 44: 
          { return TSTypes.INTERNALNAME;
          }
        case 130: break;
        case 51: 
          { return TSTypes.LOGOR;
          }
        case 131: break;
        case 64: 
          { return TSTypes.ELSE;
          }
        case 132: break;
        case 69: 
          { return TSTypes.SWITCH;
          }
        case 133: break;
        case 43: 
          { return TSTypes.MINUSMINUS;
          }
        case 134: break;
        case 24: 
          { return TSTypes.BITOR;
          }
        case 135: break;
        case 71: 
          { return TSTypes.FOREACH;
          }
        case 136: break;
        case 38: 
          { return TSTypes.DIVIDEASSIGN;
          }
        case 137: break;
        case 72: 
          { return TSTypes.DEFAULT;
          }
        case 138: break;
        case 30: 
          { return TSTypes.FLOAT;
          }
        case 139: break;
        case 65: 
          { return TSTypes.CASE;
          }
        case 140: break;
        case 50: 
          { return TSTypes.ANDASSIGN;
          }
        case 141: break;
        case 74: 
          { return TSTypes.PACKAGE;
          }
        case 142: break;
        case 18: 
          { return TSTypes.MINUS;
          }
        case 143: break;
        case 13: 
          { return TSTypes.RBRACE;
          }
        case 144: break;
        case 15: 
          { return TSTypes.RBRACK;
          }
        case 145: break;
        case 9: 
          { return TSTypes.DIVIDE;
          }
        case 146: break;
        case 54: 
          { return TSTypes.LOGAND;
          }
        case 147: break;
        case 52: 
          { return TSTypes.XORASSIGN;
          }
        case 148: break;
        case 45: 
          { return TSTypes.MINUSASSIGN;
          }
        case 149: break;
        case 25: 
          { return TSTypes.LT;
          }
        case 150: break;
        case 29: 
          { return TSTypes.CONCAT;
          }
        case 151: break;
        case 12: 
          { return TSTypes.LBRACE;
          }
        case 152: break;
        case 20: 
          { return TSTypes.ASSIGN;
          }
        case 153: break;
        case 28: 
          { return TSTypes.BITCOMPL;
          }
        case 154: break;
        case 57: 
          { return TSTypes.NOTEQUAL;
          }
        case 155: break;
        case 14: 
          { return TSTypes.LBRACK;
          }
        case 156: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
